### ISSUE TITLE
Syntax error in PocketsmithClient

### ISSUE THREAD

**Issue by mbadran** [theY4Kman/python-pocketsmith-api#1]
```python
>>> import pocketsmith
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/<redacted>/Library/Python/2.7/lib/python/site-packages/pocketsmith/__init__.py", line 71, in <module>
    from pocketsmith.pocketsmith_client import PocketsmithClient
  File "/Users/<redacted>/Library/Python/2.7/lib/python/site-packages/pocketsmith/pocketsmith_client.py", line 5
    def __init__(self, api_key: str):
                              ^
SyntaxError: invalid syntax
```

I fixed this manually by removing the `: str` label from `pocketsmith_client.py`, and then the import worked.

**Comment by theY4Kman** [comment]
Ohp, thank you — I exclusively use Python 3.8+, and use annotations without a second thought. But I see I've marked the project as 2.7+, so lemme fix this up.

I appreciate the report :)

**Comment by theY4Kman** [comment]
Hmmm, on second thought, since 2.7 is EOL, I think I'll support 3.6+ — unless you have a strong desire for 2.7.

**Comment by mbadran** [comment]
Fantastic, thanks!
